name = "Magika"
uuid = "a454fd17-9086-4fe2-b9b0-9a1c0873c51f"
version = "0.0.1"
authors = ["imohag9 <souidi.hamza90@gmail.com> and contributors"]

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
ONNXRunTime = "e034b28e-924e-41b2-b98f-d2bbeb830c6a"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
Downloads = "1.6.0"
JSON3 = "1.14.3"
LazyArtifacts = "1.11.0"
ONNXRunTime = "1.3.1"
Pkg = "1.12.0"
julia = "1"
